# Site settings
baseURL = "https://ADC-UMN.github.io"
languageCode = "en-us"
title = "App Developers Club"
theme = "syna"
enableGitInfo = true
version = "0.17.2"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "UMN App Developers Club"
  description = "University of Minnesota App Developers Club"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    #primary = "#00838F"
    primary = "#73cbff" # light blue
    #secondary = "#868e96"
    secondary = "#f27200" # orange
    success = "#008f54"
    #info = "#00c9dc"
    info = "#0086bd" # dark blue
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "#about/content"
  name = "About Us"
  weight = 20

# [[menu.main]]
#   url = "#contact"
#   name = "Contact"
#   weight = 30
# 
[[menu.footer]]
  url = "https://gopherlink.umn.edu/organization/appdevelopersclub"
  name = "Gopherlink"
  weight = 10

# [[menu.footer]]
#   url = "#"
#   name = "Long Link"
#   weight = 30
# 
# [[menu.footer]]
#   url = "#"
#   name = "Tiny Link"
#   weight = 30
# 
#[[menu.copyright_footer]]
#  url = "mailto:appdevel@umn.edu"
#  name = "email"
#  weight = 10

# [[menu.copyright_footer]]
#   url = "#"
#   name = "Another Link"
#   weight = 30

[[menu.footer_social]]
  weight = 20
  name = "facebook"
  pre = "fab fa-facebook-f"
  url = "https://www.facebook.com/appdevelopersclubumn/"

[[menu.footer_social]]
  weight = 30
  name = "github"
  pre = "fab fa-github"
  url = "https://github.com/ADC-UMN"
